# Coolify конфигурация (опционально)
# Coolify автоматически обнаружит Dockerfile, но можно настроить дополнительные параметры

version: '1.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///./notifications.db}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./notifications.db:/app/notifications.db
    restart: unless-stopped

